name: Compile CV

on:
  push:
    paths:
      - "*.tex"
      - "**/*.tex"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install LaTeX
        uses: dante-ev/latex-action@v2
        with:
          root_file: cv.tex

      - name: Upload compiled PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: cv.pdf

      - name: Commit compiled PDF back to repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add cv.pdf
          git commit -m "Auto-compile PDF" || echo "No changes"
          git push
